// Regresní test: SNMP — zapnutí a omezení community na povolené adresy.
process.env.MTU_SECRET = process.env.MTU_SECRET || 'test-secret-1234567890';
process.env.MTU_PASSWORD = process.env.MTU_PASSWORD || 'test';
process.env.DATA_DIR = process.env.DATA_DIR || require('fs').mkdtempSync(require('os').tmpdir() + '/mtu-snmp-');
const { Runner } = require('../lib/runner');
let bad = 0;
const check = (ok, msg) => { if (!ok) bad++; console.log(`${ok ? 'OK ' : 'FAIL'} ${msg}`); };
const A = ['10.107.0.0/16'];
check(Runner.snmpAddressesOk('10.107.0.0/16', A), 'přesně povolený rozsah');
check(Runner.snmpAddressesOk('10.107.252.0/24,10.107.3.1/32', A), 'užší podsítě uvnitř');
check(Runner.snmpAddressesOk('10.107.3.1', A), 'holá IP uvnitř');
check(!Runner.snmpAddressesOk('0.0.0.0/0', A), '0.0.0.0/0 = bez omezení');
check(!Runner.snmpAddressesOk('::/0', A), '::/0 = bez omezení');
check(!Runner.snmpAddressesOk('', A), 'prázdné = bez omezení');
check(!Runner.snmpAddressesOk('10.0.0.0/8', A), 'širší rozsah neprojde');
check(!Runner.snmpAddressesOk('10.107.0.0/16,192.168.1.0/24', A), 'cizí rozsah navíc neprojde');
check(Runner.snmpAddressesOk('10.107.0.0/16,10.207.0.0/16', ['10.107.0.0/16', '10.207.0.0/16']), 'víc povolených rozsahů');
const C = (name, addresses, disabled = 'false') => ({ name, addresses, disabled });
let ch = Runner.snmpChanges('false', [C('public', '0.0.0.0/0'), C('mon', '10.107.252.0/24'), C('old', '::/0', 'true')], A);
check(ch.length === 2 && ch[0].cmd === '/snmp set enabled=yes' && ch[1].cmd === '/snmp community set [find name="public"] addresses=10.107.0.0/16', 'zapnout + omezit jen public: ' + ch.map(x => x.cmd || x.desc).join(' | '));
ch = Runner.snmpChanges('true', [C('mon', '10.107.0.0/16')], A);
check(ch.length === 0, 'vše v pořádku = žádná změna');
ch = Runner.snmpChanges('true', [C('x y', '0.0.0.0/0')], A);
check(ch.length === 1 && ch[0].skip && /neobvyklé/.test(ch[0].desc), 'divný název community se nechá s varováním');
ch = Runner.snmpChanges('true', [C('public', '0.0.0.0/0', 'true')], A);
check(ch.length === 1 && ch[0].skip && /žádná zapnutá/.test(ch[0].desc), 'jen vypnuté community = varování');
(async () => {
  const cmds = [], log = [];
  const fake = { kv: async () => ({ enabled: 'false' }), list: async (menu, fields, o) => (o && o.where ? [] : [{ name: 'public', addresses: '0.0.0.0/0' }]), exec: async (cmd) => { cmds.push(cmd); return ''; } };
  const r = Object.create(Runner.prototype);
  const S = { snmp_enable: true, snmp_addresses: '10.107.0.0/16' };
  await r.setupSnmp(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), S, false);
  check(cmds.length === 2 && cmds[0] === '/snmp set enabled=yes' && /community set/.test(cmds[1]), 'ostrý běh pošle oba příkazy: ' + cmds.join(' | '));
  cmds.length = 0; log.length = 0;
  await r.setupSnmp(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), S, true);
  check(cmds.length === 0 && log.some(l => /DRY RUN SNMP/.test(l)), 'dry run jen vypíše');
  cmds.length = 0; log.length = 0;
  await r.setupSnmp(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), { snmp_enable: true, snmp_addresses: '' }, false);
  check(cmds.length === 0 && log.length === 0, 'bez adres se krok neprovádí');
  await r.setupSnmp(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), { snmp_enable: true, snmp_addresses: 'blabla' }, false);
  check(cmds.length === 0 && log.some(l => /neplatná adresa/.test(l)), 'neplatná adresa = varování');
  cmds.length = 0; log.length = 0;
  await r.setupSnmp({ ...fake, list: async () => null }, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), S, false);
  check(cmds.length === 0 && log.some(l => /nejde přečíst/.test(l)), 'menu bez community = varování, nic se nemění');
  console.log(bad ? `SELHALO: ${bad}` : 'SNMP OK');
  process.exit(bad ? 1 : 0);
})();
