// Regresní test: DNS — statické servery /ip dns přesně podle nastavení (na pořadí záleží).
process.env.MTU_SECRET = process.env.MTU_SECRET || 'test-secret-1234567890';
process.env.MTU_PASSWORD = process.env.MTU_PASSWORD || 'test';
process.env.DATA_DIR = process.env.DATA_DIR || require('fs').mkdtempSync(require('os').tmpdir() + '/mtu-dns-');
const { Runner } = require('../lib/runner');
let bad = 0;
const check = (ok, msg) => { if (!ok) bad++; console.log(`${ok ? 'OK ' : 'FAIL'} ${msg}`); };
const S = ['10.107.4.100', '10.107.4.129'];
check(Runner.dnsChanges('10.107.4.100,10.107.4.129', S).length === 0, 'shoda = nic');
check(Runner.dnsChanges('10.107.4.100;10.107.4.129', S).length === 0, 'středník (RouterOS 7.2x) = shoda');
check(Runner.dnsChanges('10.107.4.129,10.107.4.100', S).length === 1, 'jiné pořadí = změna (primární/sekundární)');
check(Runner.dnsChanges('', S).length === 1 && /žádné →/.test(Runner.dnsChanges('', S)[0].desc), 'prázdné = nastaví');
check(Runner.dnsChanges('8.8.8.8', S)[0].cmd === '/ip dns set servers=10.107.4.100,10.107.4.129', 'cizí server se přepíše celým seznamem');
(async () => {
  const cmds = [], log = [];
  const fake = { kv: async () => ({ servers: '8.8.8.8' }), exec: async (cmd) => { cmds.push(cmd); return ''; } };
  const r = Object.create(Runner.prototype);
  const st = { dns_enable: true, dns_servers: '10.107.4.100, 10.107.4.129' };
  await r.setupDns(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), st, false);
  check(cmds.length === 1 && cmds[0] === '/ip dns set servers=10.107.4.100,10.107.4.129', 'ostrý běh pošle set: ' + cmds.join(' | '));
  cmds.length = 0; log.length = 0;
  await r.setupDns(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), st, true);
  check(cmds.length === 0 && log.some(l => /DRY RUN DNS/.test(l)), 'dry run jen vypíše');
  cmds.length = 0; log.length = 0;
  await r.setupDns(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), { dns_enable: false, dns_servers: '1.1.1.1' }, false);
  check(cmds.length === 0 && log.length === 0, 'vypnuto = nic');
  await r.setupDns(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), { dns_enable: true, dns_servers: '' }, false);
  check(cmds.length === 0 && log.length === 0, 'bez serverů = nic');
  await r.setupDns(fake, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), { dns_enable: true, dns_servers: '10.107.0.0/16' }, false);
  check(cmds.length === 0 && log.some(l => /neplatná adresa/.test(l)), 'CIDR místo IP = varování');
  cmds.length = 0; log.length = 0;
  await r.setupDns({ ...fake, kv: async () => ({ servers: null }) }, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), st, false);
  check(cmds.length === 0 && log.some(l => /nejde přečíst/.test(l)), 'menu nejde přečíst = varování');
  cmds.length = 0; log.length = 0;
  await r.setupDns({ ...fake, kv: async () => ({ servers: '10.107.4.100,10.107.4.129' }) }, (lv, m) => log.push(m), (m) => log.push('warn: ' + m), st, false);
  check(cmds.length === 0 && log.some(l => /už odpovídají/.test(l)), 'shoda = jen log');
  console.log(bad ? `SELHALO: ${bad}` : 'DNS OK');
  process.exit(bad ? 1 : 0);
})();
