#!/usr/bin/env node
'use strict';
// Vykreslení všech pohledů UI bez prohlížeče (minimální náhrada DOM). Chytá ReferenceError/TypeError v šablonách,
// projde všechna řazení a filtry seznamu zařízení, přehled jobů, nápovědu, nastavení i správu. Spouští tools/preflight.sh.
const fs = require('fs'), path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8');
const mk = () => { const el = { innerHTML: '', textContent: '', value: '', checked: false, style: {}, dataset: {}, hidden: false, open: false, elements: {}, classList: { add() {}, remove() {}, toggle() {}, contains: () => false }, children: [], querySelectorAll: () => [], querySelector: () => null, addEventListener() {}, insertAdjacentHTML() {}, insertAdjacentElement() {}, appendChild() {}, remove() {}, focus() {}, reset() {}, scrollIntoView() {}, getBoundingClientRect: () => ({ top: 0 }) }; for (const k of ['onclick', 'onchange', 'onsubmit', 'ontoggle', 'oninput', 'onkeydown']) Object.defineProperty(el, k, { set() {}, get() { return null; } }); return el; };
global.window = { location: { search: '', pathname: '/mikrotik/', href: 'http://x/mikrotik/' }, innerHeight: 800, scrollY: 0, addEventListener() {}, matchMedia: () => ({ matches: false }), scrollTo() {} };
global.document = { body: mk(), documentElement: { scrollHeight: 0 }, getElementById: () => mk(), querySelector: () => mk(), querySelectorAll: () => [], createElement: () => mk(), addEventListener() {}, title: '' };
global.localStorage = { getItem: () => null, setItem() {}, removeItem() {} };
global.location = window.location; global.EventSource = function () { this.close = () => {}; }; global.FormData = function () { return { get: () => '', entries: () => [] }; };
global.fetch = async () => ({ ok: true, status: 200, json: async () => [], text: async () => '', headers: { get: () => 'application/json' } });
global.MutationObserver = function () { this.observe = () => {}; };
global.confirm = () => false; global.prompt = () => null; global.alert = () => {}; global.setInterval = () => 0; global.setTimeout = () => 0; global.requestAnimationFrame = () => 0;
let m = { exports: {} };
try { new Function('module', src + '\nmodule.exports = { state, renderDevices, renderSettings, renderJobs, renderHelp, renderJobDetail, renderRbdb, renderLinks };')(m); }
catch (e) { console.error('app.js se nenačetl:', e.message); process.exit(1); }
const { state: S, renderDevices, renderSettings, renderJobs, renderHelp, renderJobDetail, renderRbdb, renderLinks } = m.exports;
const dev = (id, extra) => ({ id, host: `10.0.0.${id}`, port: 22, name: `d${id}`, identity: `d${id}`, version: '7.24.2', board_name: 'RB', arch: 'arm', scan_status: 'ok', enabled: true, managed: true, track: 'v7-stable', owner_id: 1, flags: { uplink: { gateway: '10.0.0.1', iface: 'ether1', neighbor: null }, poe_children: [] }, parent_id: 0, packages: [], priority: 100, fw_current: '7.24.2', fw_upgrade: '7.24.2', total_hdd: 16e6, free_hdd: 2e6, total_mem: 64e6, free_mem: 30e6, last_seen_at: 1, last_scan_at: 1, ...extra });
const job = (id, extra) => ({ id, name: `job ${id}`, status: 'running', status_note: '', options: {}, counts: {}, total: 1, owner_id: 1, owner_name: 'x', created_at: 1, ...extra });
Object.assign(S, { authed: true, admin: true, auth: { sso: true, passwordLogin: false, user: { id: 1, name: 'x' }, userdb: { enabled: true, uid: 1, nick: 'n' }, serverStartedAt: Date.now(), sourceIp: '192.0.2.10', draining: false }, users: [{ id: 1, name: 'x', role: 'admin', userdb_uid: 1, userdb_nick: 'n' }], settings: { min_uptime_min: 10, default_track: 'v7-stable', allow_registration: false }, settingsOwn: {}, settingsGlobal: { min_uptime_min: 10, default_track: 'v7-stable' }, tracks: ['v7-stable', 'v7-long-term', 'v6-long-term', 'hold'], stats: { total: 3, upToDate: 1, needs: 1, stayV6: 0, unreachable: 1, upgrading: 0, hold: 0, never: 0, dead: 0, upgradedToday: 0, upgradedTotal: 0, failedTotal: 0, failedToday: 0, jobsRunning: 0, users: 1 }, runner: { running: false, busy: [], jobs: [], others: [{ uid: 5, user: 'u', total: 3, done: 1, jobs: 1 }] }, scanning: [], selected: new Set(), latest: { versions: { 'v7-stable': { version: '7.24.2' }, 'v7-long-term': { version: '7.23.5' }, 'v6-long-term': { version: '6.49.21' } } } });
S.devices = [dev(1), dev(2, { version: '6.49.10', parent_id: 1, userdb_member: 5, userdb_ap: 'AP', dup_of: 0 }), dev(3, { scan_status: 'unreachable', parent_id: 99, parent_foreign: { name: 'cizí', user: 'jiný' }, track: 'v6-long-term' }), dev(4, { dup_of: 1, enabled: false }), dev(6, { dup_of: 77, enabled: false, dup_foreign: { name: 'cizí hlavní', host: '10.9.9.9', user: 'jiný' } })];
S.jobs = [job(1, { current: { dev: 'd1', step: 'čekám na návrat routeru (1 min)', status: 'reboot' } }), job(2, { status: 'paused', status_note: 'aktualizace serveru — job pokračuje automaticky po restartu' }), job(3, { status: 'scheduled', options: { start_at: 1e10, early_precheck: { at: Date.now(), ready: 1, blocked: 1, warned: 0, reasons: ['x: y'], warns: [] } } }), job(4, { status: 'done', counts: { done: 1 } }), job(5, { status: 'queued', status_note: 'server se za chvíli aktualizuje — job se spustí hned po restartu' })];
let fail = 0;
const run = (name, f) => { const el = mk(); try { f(el); if (!el.innerHTML || el.innerHTML.length < 50) throw new Error('prázdný výstup'); console.log(`  ${name}: OK (${el.innerHTML.length} znaků)`); } catch (e) { fail++; console.log(`  ${name}: CHYBA ${e.message}`); } };
for (const adv of [false, true]) {
  S.advanced = adv;
  for (const srt of ['tree', 'priority', 'name', 'version', 'model', 'seen', 'status', 'firmware', 'track', 'owner', 'host']) for (const dir of ['asc', 'desc']) { S.sort = srt; S.sortDir = dir; run(`zařízení adv=${adv} sort=${srt}/${dir}`, renderDevices); }
  for (const vf of ['', 'v6', 'v7', 'need', 'crit', 'ok', 'bad']) { S.vf = vf; run(`zařízení filtr=${vf || 'vše'}`, renderDevices); }
  S.vf = ''; S.owner = 1; run(`zařízení vlastník adv=${adv}`, renderDevices); S.owner = 0;
  run(`zařízení duplicita u jiného správce adv=${adv}`, (el) => { renderDevices(el); if (!el.innerHTML.includes('viz hlavní (u jiný)')) throw new Error('chybí „viz hlavní (u …)“'); });
  run(`upgrady adv=${adv}`, renderJobs);
  run(`nastavení adv=${adv}`, (el) => renderSettings(el));
  run(`správa adv=${adv}`, (el) => renderSettings(el, true));
}
run('nápověda', renderHelp);
// RB-DB (správce): načítání, chyba, výpis s kusem v upgraderu / v userdb / nikde, všechny filtry, výběr
run('rbdb načítání', renderRbdb);
S.rbdb = { error: 'x' }; run('rbdb chyba', renderRbdb);
S.rbdb = { at: Date.now(), url: 'http://x/', api: true, queues: { snmp: 1, ssh: 0 }, stats: { found: 3, critical: 2, latest: 1, versions: '7.24.2' }, userdb: true, userdbError: '', rows: [{ ip: '10.0.0.1', version: '6.49.10', stp: '---', name: 'stale', seen: '', how: 'neighbors', device: { id: 1, owner: 'x' }, userdb: { ap: 'AP', area: 'O', apId: 1, areaId: 1, member: true } }, { ip: '10.0.0.2', dups: ['10.0.0.7'], serial: 'A51809A02E7E', license: 'QK0R-ZWU1', version: '6.49.10', stp: '1/2', name: 'a', seen: '1. 1.', how: 'snmp, neighbors', device: { id: 2, owner: 'x' }, userdb: { ap: 'AP', area: 'O', apId: 1, areaId: 1, member: true } }, { ip: '10.0.0.9', version: '6.42', stp: '---', name: 'b', seen: '', how: '', device: null, userdb: { ap: 'AP', area: 'O', apId: 1, areaId: 1, member: false } }, { ip: '10.0.0.8', version: '7.1', stp: '---', name: 'c', seen: '', how: '', device: null, userdb: null }, { ip: '10.0.0.3', version: '6.1', stp: '---', name: 'd', seen: '', how: '', device: { id: 3, owner: 'x' }, userdb: null }, { ip: '10.0.0.5', version: '2.18', swos: true, status: 'danger', stp: '', name: 'sw', seen: '', how: 'neighbors', device: null, userdb: { ap: 'AP', area: 'O', apId: 1, areaId: 1, member: false } }] };
S.rbdbSel = new Set(['10.0.0.2', '10.0.0.9', '10.0.0.8', '10.0.0.3', '10.0.0.5']); S.discovery = { total: 2, done: 1, open: 1, added: 0, existing: 0, foreign: [], authFailed: [], errors: [], found: [], finishedAt: 0 };
for (const f of ['', 'new', 'in', 'need', 'nowhere', 'swos']) { S.rbdbFilter = f; run(`rbdb filtr=${f || 'vše'}`, (el) => { renderRbdb(el); if (f === '' && !el.innerHTML.includes('10.0.0.9')) throw new Error('chybí řádek'); if (f === '' && !(el.innerHTML.includes('u nás 7.24.2') && el.innerHTML.includes('má RB-DB starší verzi'))) throw new Error('chybí příznak zastaralé verze RB-DB'); if (f === 'nowhere' && el.innerHTML.includes('10.0.0.9')) throw new Error('filtr nefunguje'); }); }
S.discovery = { ...S.discovery, winboxOnly: ['10.0.0.9 (x)'], authFailed: ['10.0.0.8'], errors: ['10.0.0.5 (y): v userdb chybí login/heslo — doplň', '10.0.0.3: port 22 neodpovídá'], notRouterOS: ['10.0.0.2'], foreign: [] }; S.rbdbFilter = 'prob'; run('rbdb problémy natažení', (el) => { renderRbdb(el); for (const t of ['SSH zavřené, jen Winbox', 'špatný login', 'bez loginu v userdb', 'problém při natažení (']) if (!el.innerHTML.includes(t)) throw new Error('chybí ' + t); }); S.rbdbFilter = ''; S.rbdb.rows.push({ ip: '10.9.9.9', dups: ['10.0.0.1'], version: '6.40', name: 'dupl', userdb: { ap: 'AP', area: 'O', apId: 1 } }); S.rbdbSel = new Set(['10.9.9.9']); run('rbdb pár přes další adresu + jen k upgradu', (el) => { renderRbdb(el); if (!el.innerHTML.includes('Poslat k upgradu (')) throw new Error('kus pod jinou adresou se nespároval'); if (!el.innerHTML.includes('Přeskenovat vybrané v RB-DB (1)') || !el.innerHTML.includes('fronta skeneru: snmp 1')) throw new Error('chybí přeskenování / fronty'); }); S.rbdbSel = new Set(['10.9.9.9', '10.0.0.9']); S.rbdbPending = { hosts: new Set(), ids: [] }; run('rbdb natáhnout a poslat', (el) => { renderRbdb(el); if (!el.innerHTML.includes('Natáhnout a poslat k upgradu (')) throw new Error('chybí kombinované tlačítko'); }); S.rbdbPending = null; S.rbdb.rows.pop(); S.rbdbSel = new Set(); S.rbdbDiscOpen = true; run('rbdb rozbalený výpis natažení', (el) => { renderRbdb(el); if (!el.innerHTML.includes('id="rbdbdisc" style="margin-top:10px" open')) throw new Error('výpis natažení není rozbalený'); }); S.rbdbDiscOpen = false; S.rbdbGrp = false; run('rbdb bez seskupení', (el) => { renderRbdb(el); if (el.innerHTML.includes('class="grp"')) throw new Error('hlavička APčka i bez seskupení'); }); S.rbdbGrp = true; run('rbdb po APčkách', (el) => { renderRbdb(el); if (!el.innerHTML.includes('class="grp"')) throw new Error('chybí hlavička APčka'); }); S.discovery = undefined;
// spoje: kvalita rádiových spojů (stanice ↔ sektor, klient mimo upgrader, 60 GHz, nespojená stanice), filtry, seskupení, hledání
run('spoje načítání', renderLinks);
S.links = { error: 'x' }; run('spoje chyba', renderLinks);
const B = (id, ap) => ({ id, host: `10.0.0.${id}`, label: `d${id}`, owner: 'x', ap, apId: 1, at: Math.floor(Date.now() / 1000) - 3600, scan_status: 'ok' });
S.links = { at: Math.floor(Date.now() / 1000), scanned: 3, total: 4, thresholds: { minSig: -75, minCcq: 60, minSig60: 50, maxPer: 5 }, rows: [
  { kind: 'sta', status: 'bad', sta: B(2, 'AP'), iface: 'wlan1', ssid: 'hk-ap', band: '5ghz-a/n', frequency: '5500', ap: B(1, 'AP'), apIface: 'wlan2', apMac: 'AA', signal: -81, ccq: 40, apSignal: -79, apCcq: 55, uptime: '1d2h', peerVersion: '7.24.2', at: B(2).at, apAt: B(1).at },
  { kind: 'sta', status: 'down', sta: B(3, 'AP2'), iface: 'wlan1', ssid: '', ap: null, apIface: '', apMac: '', signal: null, ccq: null, apSignal: null, apCcq: null, uptime: '', peerVersion: '', at: B(3).at, apAt: 0 },
  { kind: 'client', status: 'warn', sta: null, staMac: '00:11:22:33:44:55', iface: '', ssid: 'hk-ap', ap: B(1, 'AP'), apIface: 'wlan2', apMac: 'AA', signal: null, ccq: null, apSignal: -72, apCcq: 65, uptime: '3h', peerVersion: '6.49.10', at: 0, apAt: B(1).at },
  { kind: 'w60', status: 'ok', sta: B(5, ''), iface: 'wlan60-1', ssid: 'ptp', mode: 'ap-bridge', frequency: '58320', ap: B(99, ''), apIface: 'wlan60-1', apMac: 'BB', mcs: 8, rssi: 60, signal: 80, per: 0.1, peerMcs: 8, peerRssi: 58, peerSignal: 78, peerPer: 0, at: B(1).at, apAt: B(99).at },
] };
for (const f of ['prob', 'bad', 'down', '']) { S.linksFilter = f; run(`spoje filtr=${f || 'vše'}`, (el) => { renderLinks(el); const h = el.innerHTML; if (f === '' && !(h.includes('klient mimo upgrader') && h.includes('MCS 8') && h.includes('-81 dBm') && h.includes('nespojeno'))) throw new Error('chybí řádky'); if (f === 'bad' && h.includes('nespojeno')) throw new Error('filtr nefunguje'); }); }
S.linksFilter = ''; for (const k of ['sta', 'client', 'w60']) { S.linksKind = k; run(`spoje druh=${k}`, renderLinks); } S.linksKind = '';
S.linksQ = 'd2'; run('spoje hledání', (el) => { renderLinks(el); if (el.innerHTML.includes('klient mimo upgrader')) throw new Error('hledání nefiltruje'); }); S.linksQ = '';
S.linksGrp = false; run('spoje bez seskupení', (el) => { renderLinks(el); if (el.innerHTML.includes('class="grp"')) throw new Error('seskupeno'); }); S.linksGrp = true;
S.links.rows.push({ kind: 'sta', status: 'ok', sta: B(7, 'AP'), iface: 'wlan1', ssid: 'z', ap: { label: 'cizí sektor', owner: 'jiný', foreign: true, at: 1 }, apIface: 'wlan2', apMac: 'CC', signal: -60, ccq: 95, apSignal: null, apCcq: null, uptime: '1h', peerVersion: '', at: B(7).at, apAt: 1 });
run('spoje cizí protistrana', (el) => { renderLinks(el); if (!el.innerHTML.includes('cizí sektor') || !el.innerHTML.includes('(jiný)')) throw new Error('chybí cizí protistrana'); });
run('spoje po APčkách', (el) => { renderLinks(el); if (!el.innerHTML.includes('mimo userdb')) throw new Error('chybí skupina mimo userdb'); });
// detail jobu s položkami a logem (prefix zařízení, filtr důležitých řádků, filtr podle zařízení)
{
  const items = [{ id: 1, job_id: 1, device_id: 1, status: 'done', host: '10.0.0.1', dev_name: 'd1', identity: 'd1', board_name: 'RB', from_version: '7.23.1', to_version: '7.24.2', warnings: ['w'], plan: { canary: true } }, { id: 2, job_id: 1, device_id: 2, status: 'reboot', host: '10.0.0.2', dev_name: '', identity: 'd2', board_name: 'RB', step: 'restart', warnings: [] }];
  S.job = { job: job(1, { current: { dev: 'd2', step: 'restart', status: 'reboot' } }), items };
  S.jobLog = [{ id: 1, job_id: 1, item_id: 0, device_id: 0, ts: Date.now(), level: 'info', msg: 'Job "x" spuštěn' }, { id: 2, job_id: 1, item_id: 1, device_id: 1, ts: Date.now(), level: 'info', msg: '=== d1 (10.0.0.1) — začínám ===' }, { id: 3, job_id: 1, item_id: 1, device_id: 1, ts: Date.now(), level: 'info', msg: 'SSH připojeno' }, { id: 4, job_id: 1, item_id: 2, device_id: 2, ts: Date.now(), level: 'warn', msg: 'varování' }, { id: 5, job_id: 1, item_id: 2, device_id: 2, ts: Date.now(), level: 'error', msg: 'CHYBA: x' }];
  const held = document.querySelector; const det = mk(); document.querySelector = (s) => s === '#jobdetail' ? det : mk();
  for (const adv of [false, true]) { S.advanced = adv; S.logDev = adv ? 2 : 0; run(`detail jobu adv=${adv}`, (el) => { renderJobDetail(); el.innerHTML = det.innerHTML; if (!det.innerHTML.includes('class="nm">d1<') || !det.innerHTML.includes('class="ip">10.0.0.1<')) throw new Error('chybí prefix zařízení v logu'); if (!det.innerHTML.includes('class="info lo"')) throw new Error('chybí označení nedůležitého řádku'); }); }
  document.querySelector = held;
}
S.admin = false; S.users = null; S.settingsGlobal = undefined; run('zařízení jako uživatel', renderDevices); run('nastavení jako uživatel', (el) => renderSettings(el)); run('upgrady jako uživatel', renderJobs);
if (fail) { console.error(`UI smoke: ${fail} chyb`); process.exit(1); }
console.log('UI smoke OK');
